export const pageUrlMapping = {
    home: "/",
    dashboard: "/dashboard",
    account: "/dashboard/account",
    account_profile: "/dashboard/account/profile",
    account_settings: "/dashboard/account/settings",
    contribution: "/dashboard/contribution",
    contribution_contribute: "/dashboard/contribution/contribute",
    contribution_my_contributions: "/dashboard/contribution/my-contributions",
    moderation: "/dashboard/moderate",
    moderation_summary: "/dashboard/moderation/summary",
    moderation_pendingchallenges: "/dashboard/moderation/pending-challenges",
    moderation_reviewchallenges: "/dashboard/moderation/review-challenges",
    moderation_settings: "/dashboard/moderation/settings",
    participation: "/dashboard/participation",
    participation_explore: "/dashboard/participation/explore",
    participation_workspace: "/dashboard/participation/workspace",
    evaluation: "/dashboard/evaluation",
    evaluation_pendingsolutions: "/dashboard/evaluation/pending-solutions",
    evaluation_evaluatedbyme: "/dashboard/evaluation/evaluated-by-me",
}